title: Andrew Marques
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Andrew Marques # add your name
author-img: profile.png # add your photo
about-author: Aspiring data scientist, bookworm, occasional teacher and constant learner. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: acmarkes # add your Github handle
social-linkedin: andrew-d-20093669 # add your Linkedin handle
social-email: acmarques.ds@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 12232e #80B3FF
  primary-rgb: "18, 35, 46" #"128,179,255"
  secondary: 007cc7 #FD6E8A
  secondary-dark: 0, 124, 199 #A2122F

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
